export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 72],
    'subject-case': [2, 'never', ['pascal-case']],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [2, 'always', 'lower-case'],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'design',
        'refac',
        'test',
        'chore',
        'comment',
        'remove',
        'rename',
        'build',
        'ci',
      ],
    ],
    'scope-enum': [2, 'always', ['auth', 'ui', 'api', 'db', 'config']],
  },
};
