name: Build and Deploy to Azure

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: ✅ 코드 체크아웃
        uses: actions/checkout@v3

      - name: ✅ 환경변수 등록
        run: |
          echo "VITE_NAVER_API_CLIENT_ID=$VITE_NAVER_API_CLIENT_ID" >> .env
          echo "VITE_NAVER_API_CLIENT_SECRET_ID=$VITE_NAVER_API_CLIENT_SECRET_ID" >> .env
          echo "VITE_SERVER_API_URL=$VITE_SERVER_API_URL" >> .env
          echo "VITE_SPROUT_PUBLIC_ASSET_URL=$VITE_SPROUT_PUBLIC_ASSET_URL" >> .env
        env:
          VITE_NAVER_API_CLIENT_ID: ${{ secrets.VITE_NAVER_API_CLIENT_ID }}
          VITE_NAVER_API_CLIENT_SECRET_ID: ${{ secrets.VITE_NAVER_API_CLIENT_SECRET_ID }}
          VITE_SERVER_API_URL: ${{ secrets.VITE_SERVER_API_URL }}
          VITE_SPROUT_PUBLIC_ASSET_URL: ${{ secrets.VITE_SPROUT_PUBLIC_ASSET_URL }}

      - name: ✅ 의존성 설치
        run: |
          rm -rf package-lock.json node_modules
          npm cache clean --force
          npm install

      - name: ✅ 프로젝트 빌드
        run: npm run build

      - name:  Azure 로그인
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Blob Storage 배포
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name fedeploy \
              --destination '$web' \
              --source ./dist \
              --auth-mode login \
              --overwrite
